name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: echo "TESTDB_CONNECTION=test_db >> .env"

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker compose -f environments/docker-compose.yml build

    - name: Start Docker container
      run: docker compose -f environments/docker-compose.yml up -d

    - name: Wait for service to be ready
      run: |
        until nc -z localhost 3306; do
          sleep 1;
        done

    - name: Run tests
      run: go test ./src/...

    - name: Shut down Docker container
      run: docker compose -f environments/docker-compose.yml down
